############ ANSIBLE PARAMS ###########
timeout: 60
ansible_become: yes
ansible_ssh_user: ocpadm

######## OPENSHIFT MASTER PARAMS ###########

openshift_deployment_type: openshift-enterprise
openshift_version: "3.9.31"
openshift_disable_check: "memory_availability"
openshift_master_cluster_method: native

openshift_master_cluster_hostname: console.example.com
openshift_master_cluster_public_hostname: console-internal.example.com.com
openshift_master_api_port: 8443
openshift_master_console_port: 8443

openshift_master_default_subdomain: apps.example.com
openshift_master_overwrite_named_certificates: true

openshift_master_identity_providers:
  - name: htpasswd_auth
    login: true
    challenge: true
    kind: HTPasswdPasswordIdentityProvider
    filename: /etc/origin/master/htpasswd


openshift_hosted_registry_routehost: docker-registry.example.com


######## NETWORKING PARAMS #############
#
#
os_sdn_network_plugin_name: redhat/openshift-ovs-networkpolicy


###

########### NODES PARAMS ############### 
openshift_node_kubelet_args:
  image-gc-high-threshold: ['90']
  image-gc-low-threshold: ['80']

# Registry at the right place
openshift_hosted_registry_selector: 'region: infra-metrics'
openshift_hosted_registry_replicas: 1

# Public Router
openshift_hosted_router_replicas: 2
openshift_hosted_router_selector: 'region: infra'

# PaaS features
openshift_enable_service_catalog: false
template_service_broker_install: false

